### ISSUE TITLE
Support for Protractor v6

### ISSUE THREAD

**Issue by avient** [nils-hoyer/protractor-stop-describe-on-failure#2]
Are there plans to support Protractor v6 ?

**Comment by nils-hoyer** [comment]
I don't see any reasons, why the plugin should not work with Protractor 6 as long as you use Jasmine as test runner. What are your concerns?

**Comment by avient** [comment]
As I see it doesn't work with Protractor 6. 
Jasmine made some changes around pending/disabled specs in v.3. So maybe here is the problem

**Comment by nhoyer-extern** [comment]
I provided a fix for protractor 6.0.0. As mentioned in the jasmine source, accessing filterSpec via env is now deprecated and might be not available anymore in future releases. let me know if this is working for you @avient  

npm i protractor-stop-describe-on-failure@1.0.4

**Comment by nils-hoyer** [comment]
I provided a fix for protractor 6.0.0. As mentioned in the jasmine source, accessing filterSpec via env is now deprecated and might be not available anymore in future releases. let me know if this is not working for you @avient

npm i protractor-stop-describe-on-failure@1.0.4
